import { NgModule } from '@angular/core';

import {
  MatInputModule,
  MatCardModule,
  MatButtonModule,
  MatSidenavModule,
  MatListModule,
  MatIconModule,
  MatToolbarModule,
  MatProgressSpinnerModule,
  MatMenuModule,
  MatExpansionModule,
  MatLineModule,
  MatSortModule,
  MatChipsModule,
  MatRadioModule,
  MatTableModule,
  MatCommonModule,
  MatProgressBarModule,
  MatCheckboxModule,
  MatFormFieldModule,
  MatDialogModule,
  MatSelectModule,
  MatGridListModule
} from '@angular/material';

@NgModule({
  imports: [
    MatInputModule,
    MatCardModule,
    MatButtonModule,
    MatSidenavModule,
    MatListModule,
    MatIconModule,
    MatToolbarModule,
    MatProgressSpinnerModule,
    MatMenuModule,
    MatExpansionModule,
    MatLineModule,
    MatSortModule,
    MatChipsModule,
    MatRadioModule,
    MatTableModule,
    MatCommonModule,
    MatProgressBarModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatDialogModule,
    MatSelectModule,
    MatGridListModule
  ],
  exports: [
    MatInputModule,
    MatCardModule,
    MatButtonModule,
    MatSidenavModule,
    MatListModule,
    MatIconModule,
    MatToolbarModule,
    MatProgressSpinnerModule,
    MatMenuModule,
    MatExpansionModule,
    MatLineModule,
    MatLineModule,
    MatSortModule,
    MatChipsModule,
    MatRadioModule,
    MatTableModule,
    MatCommonModule,
    MatProgressBarModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatDialogModule,
    MatSelectModule,
    MatGridListModule
  ]
})
export class MaterialModule {}
